/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UmSpinner {}
  interface UmStockFinder {}
  interface UmStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLUmSpinnerElement extends Components.UmSpinner, HTMLStencilElement {}
  var HTMLUmSpinnerElement: {
    prototype: HTMLUmSpinnerElement;
    new (): HTMLUmSpinnerElement;
  };

  interface HTMLUmStockFinderElement extends Components.UmStockFinder, HTMLStencilElement {}
  var HTMLUmStockFinderElement: {
    prototype: HTMLUmStockFinderElement;
    new (): HTMLUmStockFinderElement;
  };

  interface HTMLUmStockPriceElement extends Components.UmStockPrice, HTMLStencilElement {}
  var HTMLUmStockPriceElement: {
    prototype: HTMLUmStockPriceElement;
    new (): HTMLUmStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'um-spinner': HTMLUmSpinnerElement;
    'um-stock-finder': HTMLUmStockFinderElement;
    'um-stock-price': HTMLUmStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface UmSpinner {}
  interface UmStockFinder {
    'onUmSymbolSelected'?: (event: CustomEvent<string>) => void;
  }
  interface UmStockPrice {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'um-spinner': UmSpinner;
    'um-stock-finder': UmStockFinder;
    'um-stock-price': UmStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'um-spinner': LocalJSX.UmSpinner & JSXBase.HTMLAttributes<HTMLUmSpinnerElement>;
      'um-stock-finder': LocalJSX.UmStockFinder & JSXBase.HTMLAttributes<HTMLUmStockFinderElement>;
      'um-stock-price': LocalJSX.UmStockPrice & JSXBase.HTMLAttributes<HTMLUmStockPriceElement>;
    }
  }
}


