/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UmStockPrice {}
}

declare global {


  interface HTMLUmStockPriceElement extends Components.UmStockPrice, HTMLStencilElement {}
  var HTMLUmStockPriceElement: {
    prototype: HTMLUmStockPriceElement;
    new (): HTMLUmStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'um-stock-price': HTMLUmStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface UmStockPrice {}

  interface IntrinsicElements {
    'um-stock-price': UmStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'um-stock-price': LocalJSX.UmStockPrice & JSXBase.HTMLAttributes<HTMLUmStockPriceElement>;
    }
  }
}


